### ISSUE TITLE
Errors while using SEMinR data analysis software

### ISSUE THREAD

**Issue by domician1** [sem-in-r/seminr#263] opened 2022-01-29 22:01 UTC
Dear members of GitHub

I have been trying to generate the results using SEMinR data analysis package. However, there appear error messages that block the output:

error 1 (pops up when trying to generate un-estimated structural model)

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  'file' must be a character string or connection

Error 2 (occurs when trying to estimate the model)

Error in matrix(unlist(construct_measurements), ncol = 3, byrow = TRUE,  : 
  'data' must be of a vector type, was 'NULL'

My code leading to the above errors

```{r}
library(seminr)
data.frame <- read.csv(datest)

##1 Specifying the measurement model & interaction terms (using default two-stage approach)
measurements <- constructs(
composite("Technology_Usage", multi_items("usecomp", "useipad", "usedcam", "usemobint", "usecompint", "useiot", "usemobm", "usecompm", "usemobs", "usemob", "usemobtx", "usebcod", "useqr", "userfid", "usemoney", "usebank", "useice", "usecold", "usebcha", "usegmap", "usegcloud")), 
composite("Behavioural_Intention", multi_items("bifuture", "bidaily", "bifreq")), 
composite("Performance_Expectancy", multi_items("peuse", "peach", "pecost", "pepdvty", "peprofit", "petzpric", "peukpric", "pefshgov"))
)

#2 Specifying the Structural Model
structural <- relationships(
paths(from = "Performance_Expectancy", to = "Behavioural_Intention"),
paths(from = "Effort_Expectancy", to = "Behavioural_Intention"),
paths(from = "Social_Influence", to = "Behavioural_Intention"),
paths(from = "Facilitating_Conditions", to = c("Behavioural_Intention", "Technology_Usage")),
paths(from = "Hedonic_Motivation", to = "Behavioural_Intention"),
paths(from = "Price_Value", to = "Behavioural_Intention")
)
[datest.xlsx](https://github.com/sem-in-r/seminr/files/7964821/datest.xlsx)


#3 Visualising the Non-Estimated Structural Model
library("DiagrammeR")
data.frame <- read.csv(datest)
plot(structural)

#4 Estimating the Model
library(seminr)
model_datest <- estimate_pls(
data = datest
)
```

**Comment by soumyaray** [comment] 2022-01-31 07:15
Hi @domician1 and thanks for trying out SEMinR.  The major issue you are having is that you have not loaded the data correctly. Might I suggest the following:

1. Use your browser to go to https://github.com/sem-in-r/seminr/files/7964821/datest.xlsx and download that file into the working directory of your project – having a local copy of the data file will allow you to run your code even when you are offline
2. Use Excel to open that datast.xlsx file and save it as a CSV file (Excel has that option if you save as or export) to make a datest.csv file
3. Change line 2 to `my_data <- read.csv("datest.csv')` – two things here: don't call your data data.frame as that is already the name of a class of objects in R; and you need to put quotes around the filename.
4. Remove the line `[datest.xlsx](https://github.com/sem-in-r/seminr/files/7964821/datest.xlsx)` – that is not valid R syntax (it belongs in a RMarkdown file, which your code is not)
5. Remove the two line under `#3 Visualizing...` that says `library("DiagrammeR") and `data.frame <- read.csv(datest)` as you don't need to keep loading libraries and reading the data repeatedly

Your final code might look something like this (after separately doing steps 1 and 2 above):

```
library(seminr)
datest <- read.csv("datest.csv")

##1 Specifying the measurement model & interaction terms (using default two-stage approach)
measurements <- constructs(
  composite("Technology_Usage", multi_items("usecomp", "useipad", "usedcam", "usemobint", "usecompint", "useiot", "usemobm", "usecompm", "usemobs", "usemob", "usemobtx", "usebcod", "useqr", "userfid", "usemoney", "usebank", "useice", "usecold", "usebcha", "usegmap", "usegcloud")), 
  composite("Behavioural_Intention", multi_items("bifuture", "bidaily", "bifreq")), 
  composite("Performance_Expectancy", multi_items("peuse", "peach", "pecost", "pepdvty", "peprofit", "petzpric", "peukpric", "pefshgov"))
)

#2 Specifying the Structural Model
structural <- relationships(
  paths(from = "Performance_Expectancy", to = "Behavioural_Intention"),
  paths(from = "Effort_Expectancy", to = "Behavioural_Intention"),
  paths(from = "Social_Influence", to = "Behavioural_Intention"),
  paths(from = "Facilitating_Conditions", to = c("Behavioural_Intention", "Technology_Usage")),
  paths(from = "Hedonic_Motivation", to = "Behavioural_Intention"),
  paths(from = "Price_Value", to = "Behavioural_Intention")
)

#3 Visualising the Non-Estimated Structural Model
plot(structural)

#4 Estimating the Model
model_datest <- estimate_pls(
  data = datest,
  measurement_model = measurements,
  structural_model = structural
)
```

I haven't tried the code above yet so let me know if you encounter more errors.

**Comment by domician1** [comment] 2022-01-31 19:15
Thanks soumyaray, I will give it a try tomorrow and update you on the results

**Comment by domician1** [comment] 2022-02-01 21:52
Dear soumyaray, thanks again for your support. 

However, when I attempted to extend the application of your proposed corrections to my initial code, I was only able to generate the plot for un-estimated model (see attached). The code to estimate and generate the model failed with many errors returned (see attached doc showing the codes and the corresponding error returns).

May I now ask for guidance to correct the code, especially on how to make R recognise the key objects (because most errors are about 'object....not found'). I attach the error doc and the data used.

Thanks in advance
Charles
[datest2.csv](https://github.com/sem-in-r/seminr/files/7982151/datest2.csv)
[EXECUTED R SCRIPT & ERRORS.docx](https://github.com/sem-in-r/seminr/files/7982152/EXECUTED.R.SCRIPT.ERRORS.docx)
![Rplot-SEMinR unestimated 1 2 2022](https://user-images.githubusercontent.com/98668993/152057610-e60d99ba-7476-4657-a6b5-17cff4ef54ae.png)

**Comment by sandeepdey98** [comment] 2022-02-04 09:44
Dear Saumya da,
real sorry for troubling you and the other team members.
I have travelled everywhere on YT and other places to get to the bottom of this error. Any heads up from you will be highly appreciated...
##start code
library(seminr)
attach(GreenPB)
survey.data<- GreenPB
#measurement model
measurement<- constructs(
  composite("ATT", multi_items("ATT", 1:5)),
  composite("INT", multi_items("INT", 1:3)),
  composite("PAE", multi_items("PAE", 1:4)),
  composite("NAE", multi_items("NAE", 1:4)),
  composite("SUB", multi_items("SUB", 1:3)),
  composite("PBC", multi_items("PBC", 1:3)),
  composite("DES", multi_items("DES", 1:3)),
  composite("GRE", multi_items("GRE", 1:5)),
  composite("DGB", multi_items("DGB", 1:3)),
  composite("MDF", multi_items("MDF", 1:4)), 
  composite("GPB", multi_items("GPB", 1:4)))
  interaction_term(iv="INT", moderator = "GRE", method = product_indicator)
  interaction_term(iv="INT", moderator = "MDF", method = product_indicator)

#structural model
structure<- relationships(
  paths(from = "ATT", to="DES"),
paths(from = "PAE", to="DES"),
paths(from = "NAE", to="DES"),
paths(from = "SUB", to="DES"),
paths(from = "PBC", to="DES"),
paths(from = "DES", to="INT"),
paths(from=  "INT", to="GPB"),
paths(from = "DGB", to = "GPB"),
paths(from = "PBC", to="GPB"),
paths(from = "INT*GRE", to= "GPB"),
paths(from = "INT*MDF", to="GPB"))
# estimating model
greenpb_pls <- estimate_pls(
  data = survey.data,
  measurement_model = measurement,
  structural_model = structure,
  inner_weights = path_weighting
)
-> and then this error happens :(
Generating the seminr model
All 101 observations are valid.
Error in measurement_mode_scheme[[i]](mmMatrix, i, normData, construct_scores) : 
  attempt to apply non-function

**Comment by domician1** [comment] 2022-02-04 10:08
Dear soumyaray
Is this last post the way my problem can be solved or it's just another challenge similar to mine?
Please advise
Thanks
Charles

**Comment by sandeepdey98** [comment] 2022-02-04 14:45
> Dear soumyaray Is this last post the way my problem can be solved or it's just another challenge similar to mine? Please advise Thanks Charles

This is an error similar to yours Mr. Charles.

**Comment by soumyaray** [comment] 2022-02-07 02:34
@domician1 

Your model is extremely complicated! I'm not entirely sure it will be valid to have so many constructs and paths for only 500+ observations. Nonetheless, I've tried running a simpler model to start:

```r
datest_mm_simple <- constructs(
  composite("Technology_Usage", multi_items("USE", 1:21)),
  composite("Behavioural_Intention", multi_items("BI", 1:3)),
  composite("Performance_Expectancy", multi_items("PE", 1:8)),
  composite("Effort_Expectancy", multi_items("EE", 1:4)),
  composite("Social_Influence", multi_items("SI", 1:3)),
  composite("Facilitating_Conditions", multi_items("FC", 1:4)),
  composite("Hedonic_Motivation", multi_items("HM", 1:3)),
  composite("Price_Value", multi_items("PV", 1:3)),
  composite("HabiT", multi_items("HT", 1:4)),
  composite("FISHERY", single_item("fishery")),
  composite("GENDER", single_item("gender")),
  composite("AGE", single_item("age")),
  composite("EXPERIENCE", single_item("experience")),
  composite("PRICE", single_item("price")),
  composite("LABOUR", single_item("labour")),
  composite("COST", single_item("cost")),
  composite("PROFITABILITY", single_item("profit")),
  composite("EDUCATION", single_item("education")),
  composite("FISHING_MONTHS", single_item("fishingmonths"))
)

datest_sm_simple <- relationships(
  paths(from=c("Performance_Expectancy", "Effort_Expectancy", "Social_Influence",
             "Facilitating_Conditions", "Hedonic_Motivation", "Price_Value", "HabiT",
             "FISHERY", "GENDER", "AGE", "EXPERIENCE", "PRICE", "LABOUR", "COST",
             "PROFITABILITY", "EDUCATION", "FISHING_MONTHS"),
        to = "Behavioural_Intention"),
  paths(from="Behavioural_Intention", to="Technology_Usage")
)

seminr_model <- estimate_pls(data = datest2,
                             measurement_model = datest_mm_simple,
                             structural_model = datest_sm_simple)
```

This model runs fine. Could I ask you to confirm this runs and then add necessary things one-by-one until you find the point where you get an error?

Also, please see how I am using markdown syntax in my comments here to format the code. Please use the same rather than sending word documents (Word corrupts the code by changing characters).

**Comment by soumyaray** [comment] 2022-02-07 02:37
@sandeepdey98 Similarly to my advice for @domician1, could I kindly ask you to start with the simplest model possible that runs (e.g., a few constructs and no interactions) and slowly add complexity (first add more constructs and rerun, and add interactions at the end) until you find what is causing the error?

**Comment by sandeepdey98** [comment] 2022-02-07 15:37
@soumyaray da,
My professor helped me figure out the cause of the error. All this while I was not including the interaction terms in the measurement object...I was forgetting to add the closing bracket. The code and the moderators work fine. I apologize for this, I'd just lost my mind. 

The script should look like this:
library(seminr) # install.packages("seminr")
surveyData <- read.csv("GreenPB.csv") 
## establishing the measurement model
measurement <- constructs(
  composite("ATT", multi_items("ATT", 1:5)),
  composite("INT", multi_items("INT", 1:3)),
  composite("PAE", multi_items("PAE", 1:4)),
  composite("NAE", multi_items("NAE", 1:4)),
  composite("SUB", multi_items("SUB", 1:3)),
  composite("PBC", multi_items("PBC", 1:3)),
  composite("DES", multi_items("DES", 1:3)),
  composite("GRE", multi_items("GRE", 1:5)),
  composite("DGB", multi_items("DGB", 1:3)),
  composite("MDF", multi_items("MDF", 1:4)), 
  composite("GPB", multi_items("GPB", 1:4)),
  interaction_term(iv="INT", moderator = "GRE", method = product_indicator),
  interaction_term(iv="INT", moderator = "MDF", method = product_indicator)
 )

structure <- relationships(
 paths(from = "ATT", to="DES"),
 paths(from = "PAE", to="DES"),
 paths(from = "NAE", to="DES"),
 paths(from = "SUB", to="DES"),
 paths(from = "PBC", to="DES"),
 paths(from = "DES", to="INT"),
 paths(from = "INT", to="GPB"),
 paths(from = "DGB", to="GPB"),
 paths(from = "PBC", to="GPB"),
 paths(from = "INT*GRE", to="GPB"),
 paths(from = "INT*MDF", to="GPB")
)

greenpbPLS <- estimate_pls(
  data = surveyData,
  measurement_model = measurement,
  structural_model = structure,
  inner_weights = path_weighting
)

**Comment by soumyaray** [comment] 2022-02-08 00:54
@sandeepdey98 Glad to see you got it working and many thanks to your professor for finding the issue!

**Comment by sandeepdey98** [comment] 2022-02-17 16:43
@soumyaray da, sorry for the repeat.. this time I followed every rule in the book..this time my professor also not able to understand


library(seminr)
attach(GreenPB)
survey.data<- GreenPB
View(GreenPB)
str(survey.data)
dim(survey.data)
measurement<- constructs(
  composite("ATT", multi_items("ATT", 1:5)),
  composite("INT", multi_items("INT", 1:3)),
  composite("PAE", multi_items("PAE", 1:4)),
  composite("NAE", multi_items("NAE", 1:4)),
  composite("SUB", multi_items("SUB", 1:3)),
  composite("PBC", multi_items("PBC", 1:3)),
  composite("DES", multi_items("DES", 1:3)),
  composite("GRE", multi_items("GRE", 1:5)),
  composite("DGB", multi_items("DGB", 1:3)),
  composite("MDF", multi_items("MDF", 1:4)), 
  composite("GPB", multi_items("GPB", 1:4)),
  interaction_term(iv="INT", moderator = "GRE", method = product_indicator),
  interaction_term(iv="INT", moderator = "MDF", method = product_indicator))

structure<- relationships(
  paths(from = "ATT", to="DES"),
paths(from = "PAE", to="DES"),
paths(from = "NAE", to="DES"),
paths(from = "SUB", to="DES"),
paths(from = "PBC", to="DES"),
paths(from = "DES", to="INT"),
paths(from=  "INT", to="GPB"),
paths(from = "DGB", to = "GPB"),
paths(from = "PBC", to="GPB"),
paths(from = "INT*GRE", to= "GPB"),
paths(from = "INT*MDF", to="GPB"))
      
greenpb_pls <- estimate_pls(
  data = survey.data,
  measurement_model = measurement,
  structural_model = structure,
  inner_weights = path_weighting
)

greenpb_cfa <- estimate_cfa(
  data = survey.data,
  measurement_model = as.reflective(measurement)
)
boot_greenpb_pls <- bootstrap_model(seminr_model = greenpb_pls,
                                 nboot = 1000,
                                 cores = 2)
summary(greenpb_pls)
summary(boot_greenpb_pls)

boot_estimates <- bootstrap_model(greenpb_pls, nboot = 100, cores = 1)
plot(boot_estimates, title = "Bootstrapped Model")

**Error in model$outer_loadings[indicator, construct] : 
  subscript out of bounds**

**Comment by soumyaray** [comment] 2022-02-18 10:04
Hi @sandeepdey98 I'm happy to take a look but your code is not showing accurately on Github because some characters (like asterisks '*') are interpreted as italics, etc. Also, indentation is not showing up. Could you edit your comment and use [triple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) around your code to create a code block?

**Comment by soumyaray** [comment] 2022-02-18 10:04
and @sandeepdey98 at this point I would also suggest you start a new issue!

**Comment by NicholasDanks** [comment] 2022-03-16 15:59
@sandeepdey98 @domician1 has this issue been resolved? If so, please close the issue. 
If not, please do as @soumyaray is suggesting and share the code in a code block. this is achieved by using three backticks (`) and you can find more details here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks 

Thanks.
Nick

**Comment by sandeepdey98** [comment] 2022-03-17 12:27
Hello Nick,
I started a different issue as recommended by Dr. Roy. My issue is resolved and that particular issue was closed by me. This particular issue was activated by @domician1.

**Comment by soumyaray** [comment] 2022-03-17 12:32
thanks @sandeepdey98!

@domician1 i'll close this issue but feel free to reopen it if you still have problems.

**Closed by soumyaray** 2022-03-17 12:32 UTC
