### ISSUE TITLE
Error in if ((mmMatrix[mmMatrix[, "construct"] == construct, "type"][1] ==  :    missing value where TRUE/FALSE needed"

### ISSUE THREAD

**Issue by hagemeis** [sem-in-r/seminr#337] opened 2023-09-04 19:04 UTC
Hi,

I am trying to follow the examples in the book "Partial Least Squares Structural Equation Modeling (PLS-SEM) Using R" by Hair et al., using their syntax and their data for the example.
 

I get the error
"Generating the seminr model
All 344 observations are valid.
Error in if ((mmMatrix[mmMatrix[, "construct"] == construct, "type"][1] ==  : 
  missing value where TRUE/FALSE needed"

My syntax is (sorry if there is too much of it, it is my first question here):

library(seminr)

corp_rep_data <- read.csv(file = "c:/carmen/dienst/statistik/r_sem_buch/data_raw/Corporate Reputation Data.csv", header = TRUE, sep = ";")

#Create measurement model
simple_mm <- constructs(
  composite("COMP", multi_items("comp_", 1:3)),
  composite("LIKE2", multi_items("like_", 1:3)),
  composite("CUSA", single_item("cusa")),
  composite("CUSL", multi_items("cusl_", 1:3)))

#Create structural model
simple_sm <- relationships(
  paths(from = c("COMP", "LIKE"), to = c("CUSA", "CUSL")),
  paths(from = c("CUSA"), to = c("CUSL")))

#Estimate the model with default settings
corp_rep_simple_model <- estimate_pls(data = corp_rep_data,
                                      measurement_model = simple_mm,
                                      structural_model = simple_sm,
                                      missing_value = "-99")

I had tried the more complex estimation and got exactly the same error code.

Thank you very much for your help!
Carmen

**Comment by soumyaray** [comment] 2023-09-05 03:28
Hi @hagemeis and thanks for your note. The issue is likely that your measurement model has a construct called `LIKE2` but you are referring to `LIKE` in the structural model.  The issue is most likely as simple as fixing the construct name to be consistent.

**Comment by hagemeis** [comment] 2023-09-05 04:58
Hi  soumyaray,

thank you very much!
I am sorry. I added this typo when changing the quotation marks to a version which R can use.

Best,
Carmen

**Comment by soumyaray** [comment] 2023-09-05 07:38
Not at all -- typos happen! Closing this issue for now.

**Closed by soumyaray** 2023-09-05 07:38 UTC
