### ISSUE TITLE
Bug in bootstrapped interactions with PLSc

### ISSUE THREAD

**Issue by storopoli** [sem-in-r/seminr#84] opened 2018-10-09 08:25 UTC
```
#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  reflective("IP", multi_items("X", 1:21)),
  composite("CO", single_item("PECI"), weights = mode_A),
  reflective("Acquiescence", multi_items("AQ", 1:3)),
  reflective("Compromise", multi_items("COMP", 1:3)),
  reflective("Avoid", multi_items("AVO", 1:3)),
  reflective("Defy", multi_items("DEF", 1:4)),
  reflective("Manipulate", multi_items("MAN", 1:3)),
  reflective("Control", single_item("Control_Var_2"))
  )
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("IP", "CO"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = "IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "Control", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "IP*CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data,
                         measurement_model = model1_mm,
                         interactions = model1_xm,
                         structural_model = model1_sm,
                         inner_weights = path_weighting)
```

Gives this error

> Generating the seminr model
> All 96 observations are valid.
> Error in mm[mm[, "construct"] == construct2, ][, "measurement"] : 
>   incorrect number of dimensions

this is my names(data)
```
names(data)
  [1] "Response_ID"      "IP_Address"       "Timestamp"        "Duplicate"        "Time_Taken"      
  [6] "Seq_Number"       "Country_Code"     "Region"           "Response_Status"  "Browser"         
 [11] "Device"           "Operating_System" "Language"         "Q45"              "Qualificadora"   
 [16] "X1"               "X2"               "X3"               "X4"               "X5"              
 [21] "X6"               "X7"               "X8"               "X9"               "X10"             
 [26] "X11"              "X12"              "X13"              "X14"              "X15"             
 [31] "X16"              "X17"              "X18"              "X19"              "X20"             
 [36] "X21"              "AQ1"              "AQ2"              "AQ3"              "COMP1"           
 [41] "COMP2"            "COMP3"            "AVO1"             "AVO2"             "AVO3"            
 [46] "DEF1"             "DEF2"             "DEF3"             "DEF4"             "MAN1"            
 [51] "MAN2"             "MAN3"             "X38"              "X39"              "X40"             
 [56] "X41"              "X42"              "X43"              "X44"              "X45"             
 [61] "X46"              "X47"              "X48"              "X49"              "X50"             
 [66] "X51"              "X52"              "X53"              "X54"              "X55"             
 [71] "X56"              "X57"              "X58"              "X59"              "X60"             
 [76] "X61"              "X62"              "X63"              "X64"              "X65"             
 [81] "X66"              "X67"              "X68"              "X69"              "X70"             
 [86] "X71"              "X72"              "X73"              "X74"              "X75"             
 [91] "X76"              "X77"              "X78"              "X79"              "X80"             
 [96] "X81"              "X82"              "Priority_Time"    "Priority_Cost"    "Priority_Scope"  
[101] "Control_Var_1"    "Control_Var_2"    "Control_Var_3"    "Opinion_Survey"   "PECI"  
```

**Comment by soumyaray** [comment] 2018-10-09 08:31
Hi @storopoli thanks for reporting this. We'll try to recreate the problem as best we can ourselves first. Quick question: before you constructed this full model, did you get it working on any simpler versions of this model yet? (e.g., without interaction or with fewer constructs)

**Comment by storopoli** [comment] 2018-10-09 08:59
I've managed one time to make it work with just paths from IP to Acquiescence, Compromise, Avoid, Defy, Manipulate. No interactions.
Unfortunately, I cannot provide the data because it's from my PhD Student's dissertation.

**Comment by storopoli** [comment] 2018-10-09 10:06
I've shortened as a primary option, but I was getting the error so I thought that maybe if I explicitly wrote the paths would solve it. Thanks!

**Comment by storopoli** [comment] 2018-10-09 19:41
Same with my other PhD Student thesis

```
#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  reflective("PPM", multi_items("PCA_PPM_", 1:11)),
  composite("IUTEC", single_item("IUTEC1"), weights = mode_A),
  reflective("REGION_GLOBAL", single_item("RERES1")),
  reflective("INDUSTRY", single_item("TPIND1")),
  reflective("FIRM_SIZE", single_item("TORG1")),
  reflective("FIRM_AGE", single_item("NAEO1")),
  reflective("PPM_AGE",single_item("TOGPP1")),
  composite("GAETI", multi_items("PCA_GAETI_", 1:6))
)
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("PPM", "IUTEC"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = c("PPM","IUTEC", "PPM*IUTEC", "REGION_GLOBAL", "INDUSTRY", "FIRM_SIZE",
                 "FIRM_AGE", "PPM_AGE"), to = "GAETI"))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data_PCA,
                           measurement_model = model1_mm,
                           interactions = model1_xm,
                           structural_model = model1_sm,
                           inner_weights = path_weighting)
```

> Error in mm[mm[, "construct"] == construct2, ][, "measurement"] : 
  incorrect number of dimensions

**Comment by NicholasDanks** [comment] 2018-10-10 03:42
Dear @storopoli I hope you are well. 
I have attended to the bug in the code. This is a simple solution and we will strive to submit a fully corrected and tested seminr package to CRAN ASAP. In the interim, you can do the following:

(1) Run ```devtools::install_github("sem-in-r/seminr", ref = "single_item_interactions")``` to install the latest version from the branch attending to this bug.

(2) Change the order of the name of your interaction to be:
```model1_xm <- interactions(
  interaction_ortho("CO", "IP"))```
And remember to change the construct name in structural model.

(3) Please note that models with interactions and PLSc can be biased as per:Becker et al. (2018)
        'Estimating Moderating Effects in PLS-SEM and PLSc-SEM: Interaction Term Generation*Data Treatment'

(4) Your new code should look like this:
```#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  reflective("IP", multi_items("X", 1:21)),
  composite("CO", single_item("PECI"), weights = mode_A),
  reflective("Acquiescence", multi_items("AQ", 1:3)),
  reflective("Compromise", multi_items("COMP", 1:3)),
  reflective("Avoid", multi_items("AVO", 1:3)),
  reflective("Defy", multi_items("DEF", 1:4)),
  reflective("Manipulate", multi_items("MAN", 1:3)),
  reflective("Control", single_item("Control_Var_2"))
)
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("CO", "IP"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = "IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "Control", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO*IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data_model1,
                           measurement_model = model1_mm,
                           interactions = model1_xm,
                           structural_model = model1_sm,
                           inner_weights = path_weighting)```

**Comment by storopoli** [comment] 2018-10-10 08:06
Dear @NicholasDanks,
Thank you for the swift reply.
I've installed the version you specified.

In both tries with the two models (from both PhD Students) I get the same error

```
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
```

**Comment by storopoli** [comment] 2018-10-10 10:58
Don't know if this helps. But this is are the names of my dataset

`names(data)`
```
  [1] "Response_ID"      "IP_Address"       "Timestamp"        "Duplicate"        "Time_Taken"      
  [6] "Seq_Number"       "Country_Code"     "Region"           "Response_Status"  "Browser"         
 [11] "Device"           "Operating_System" "Language"         "Q45"              "Qualificadora"   
 [16] "X1"               "X2"               "X3"               "X4"               "X5"              
 [21] "X6"               "X7"               "X8"               "X9"               "X10"             
 [26] "X11"              "X12"              "X13"              "X14"              "X15"             
 [31] "X16"              "X17"              "X18"              "X19"              "X20"             
 [36] "X21"              "AQ1"              "AQ2"              "AQ3"              "COMP1"           
 [41] "COMP2"            "COMP3"            "AVO1"             "AVO2"             "AVO3"            
 [46] "DEF1"             "DEF2"             "DEF3"             "DEF4"             "MAN1"            
 [51] "MAN2"             "MAN3"             "X38"              "X39"              "X40"             
 [56] "X41"              "X42"              "X43"              "X44"              "X45"             
 [61] "X46"              "X47"              "X48"              "X49"              "X50"             
 [66] "X51"              "X52"              "X53"              "X54"              "X55"             
 [71] "X56"              "X57"              "X58"              "X59"              "X60"             
 [76] "X61"              "X62"              "X63"              "X64"              "X65"             
 [81] "X66"              "X67"              "X68"              "X69"              "X70"             
 [86] "X71"              "X72"              "X73"              "X74"              "X75"             
 [91] "X76"              "X77"              "X78"              "X79"              "X80"             
 [96] "X81"              "X82"              "Priority_Time"    "Priority_Cost"    "Priority_Scope"  
[101] "Control_Var_1"    "Control_Var_2"    "Control_Var_3"    "Opinion_Survey"   "PECI"  
```

**Comment by NicholasDanks** [comment] 2018-10-11 13:55
Dear @storopoli 
I believe the latest updates have attended to the bug. Can I ask you to try re-install the package using
```devtools::install_github("sem-in-r/seminr", ref = "single_item_interactions")```
and run the models. 
Please let us know if you still encounter any problems.

**Comment by storopoli** [comment] 2018-10-11 17:53
Dear @NicholasDanks 
I am still getting an error
```
Generating the seminr model
All 96 observations are valid.
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
```

**Comment by soumyaray** [comment] 2018-10-12 09:41
Hi @storopoli could you kindly run it one more time to reproduce that error, and then at the console immediately run: `traceback()`

That should give us an idea of which line and path of execution is causing the problem.

**Comment by storopoli** [comment] 2018-10-12 12:29
@soumyaray 
Of course, here it is
```
> # Load data, assemble model, and estimate using simplePLS
> model1_pls <- estimate_pls(data = data,
+                          measurement_model = model1_mm,
+                          interactions = model1_xm,
+                          structural_model = model1_sm,
+                          inner_weights = path_weighting)
Generating the seminr model
All 96 observations are valid.
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
> traceback()
8: stop("0 (non-NA) cases")
7: lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)
6: stats::lm(formula = frmla, data = data)
5: intxn_function(data, mm)
4: FUN(X[[i]], ...)
3: lapply(all_intxns, create_interaction)
2: interactions(data, measurement_model)
1: estimate_pls(data = data, measurement_model = model1_mm, interactions = model1_xm, 
       structural_model = model1_sm, inner_weights = path_weighting)
```

**Comment by soumyaray** [comment] 2018-10-12 12:43
Hi @storopoli could you kindly run a few tests for us?

1. Please reproduce that error you got, and then at the console immediately run: `traceback()` –– That should give us an idea of which line and path of execution is causing the problem.

2. Can you confirm that if you replace the single-item moderator with another multi-item construct, that everything works? Just want to make sure that its the single-item construct that's causing the problem.

3. Can you see what happens if you change `reflective("IP", multi_items("X", 1:21)` to `reflective("IP", multi_items("X", 1:3)` — we'd like to see if the number of items is an issue.

**Comment by storopoli** [comment] 2018-10-12 16:04
@soumyaray 
Sure

1) The traceback is the same
```
> traceback()
8: stop("0 (non-NA) cases")
7: lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)
6: stats::lm(formula = frmla, data = data)
5: intxn_function(data, mm)
4: FUN(X[[i]], ...)
3: lapply(all_intxns, create_interaction)
2: interactions(data, measurement_model)
1: estimate_pls(data = data, measurement_model = model1_mm, interactions = model1_xm, 
       structural_model = model1_sm, inner_weights = path_weighting)
```

2) I've managed to make the Moderator Construct as a multi-item formative construct
```
#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  reflective("IP", multi_items("X", 1:21)),
  composite("CO", multi_items("X", 41:43), weights = mode_A),
  reflective("Acquiescence", multi_items("AQ", 1:3)),
  reflective("Compromise", multi_items("COMP", 1:3)),
  reflective("Avoid", multi_items("AVO", 1:3)),
  reflective("Defy", multi_items("DEF", 1:4)),
  reflective("Manipulate", multi_items("MAN", 1:3)),
  reflective("Control", single_item("Control_Var_2"))
  )
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("CO", "IP"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = "IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "Control", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO*IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data,
                         measurement_model = model1_mm,
                         interactions = model1_xm,
                         structural_model = model1_sm,
                         inner_weights = path_weighting)
```
I get an error and here is traceback()
```
Generating the seminr model
All 96 observations are valid.
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
> traceback()
8: stop("0 (non-NA) cases")
7: lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)
6: stats::lm(formula = frmla, data = data)
5: intxn_function(data, mm)
4: FUN(X[[i]], ...)
3: lapply(all_intxns, create_interaction)
2: interactions(data, measurement_model)
1: estimate_pls(data = data, measurement_model = model1_mm, interactions = model1_xm, 
       structural_model = model1_sm, inner_weights = path_weighting)
```

3)Also getting the same error
```
#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  reflective("IP", multi_items("X", 1:3)),
  composite("CO", single_item("PECI"), weights = mode_A),
  reflective("Acquiescence", multi_items("AQ", 1:3)),
  reflective("Compromise", multi_items("COMP", 1:3)),
  reflective("Avoid", multi_items("AVO", 1:3)),
  reflective("Defy", multi_items("DEF", 1:4)),
  reflective("Manipulate", multi_items("MAN", 1:3)),
  reflective("Control", single_item("Control_Var_2"))
  )
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("CO", "IP"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = "IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "Control", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO*IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data,
                         measurement_model = model1_mm,
                         interactions = model1_xm,
                         structural_model = model1_sm,
                         inner_weights = path_weighting)

```
And here is the error and traceback()
```
Generating the seminr model
All 96 observations are valid.
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
> traceback()
8: stop("0 (non-NA) cases")
7: lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)
6: stats::lm(formula = frmla, data = data)
5: intxn_function(data, mm)
4: FUN(X[[i]], ...)
3: lapply(all_intxns, create_interaction)
2: interactions(data, measurement_model)
1: estimate_pls(data = data, measurement_model = model1_mm, interactions = model1_xm, 
       structural_model = model1_sm, inner_weights = path_weighting)
```

I am attaching the dataset and the code for you to see

[R SEMinR.zip](https://github.com/sem-in-r/seminr/files/2473782/R.SEMinR.zip)

**Comment by soumyaray** [comment] 2018-10-16 12:09
Dear @storopoli thanks to your files, we have fixed the issue — we'll send a resolution in the next 24 hours. Thanks for your patience!

**Comment by storopoli** [comment] 2018-10-16 13:18
Thank you looking forward to it

**Comment by NicholasDanks** [comment] 2018-10-17 01:59
Dear @stropoli, thank you for providing your code and data to allow us to resolve this issue.

We found a couple of issues:
We had to fix how we estimate models with single-item constructs involved in interactions.
The xlsx library was creating an unusual object that created further problems.

The single_item_interaction branch resolves problem (a) above. Please use this branch until we release a new patched version of SEMinR to CRAN.

To fix problem (b), we had to slightly modify your code, without changing its functionality. Below find the revised code below.
We used Excel to save your XLSX file as a CSV file. Then, we loaded the CSV using read.csv(). We request you kindly do this as well.
We modified the replace missing values loop to start at column 16, as the previous columns are char or factors.

After doing the above fixes, your model can be estimated just fine!

However, there is another issue that we cannot resolve. This model, with mixed composite and reflective factors and interaction, cannot be bootstrapped. This is not a bug in our code but an unresolved issue with PLSc in complex models. I have reproduced this same phenomena in SmartPLS V3 with your data, and the literature provides no guidance as to how to proceed in this scenario.

In more technical terms, some subsamples in the bootstrap produce negative rhoA values and the correction for PLSc cannot be calculated. We will consider it an ongoing problem that we will raise with the community of PLS methodologists.

For now, we suggest keeping all the constructs as composites (you may choose mode A or mode B). If you do so, bootstrapping can proceed normally. Please see this change in our solution code below.

Thank you again for assisting us to improve the quality of the SEMinR package. We will incorporate these updates in a V 0.5.3 shortly. If you require any more assistance, or spot any further bugs, please do not hesitate to contact us.

Kind regards,
SEMinR team

```
devtools::install_github("sem-in-r/seminr", ref = "single_item_interactions")
library(seminr)

# library(xlsx)
# options(scipen = 999)
# options(digits = 3)
set.seed(1)
#### Loding the Dataset ####
# please save your XLSX data sheet as a CSV file: Base_08_10_96_resp_SR_IP_only.csv

data <- read.csv(file = "Base_08_10_96_resp_SR_IP_only.csv")
names(data)
#attach(data)

#Replacing missing with mean####
#(14 missing de CO e Control)
for(i in 16:ncol(data)){
  data[is.na(data[,i]), i] <- mean(data[,i], na.rm = TRUE)
}

#Computing the PECI####
#Project Execution Complexity Index

data$PECI <- (((apply(data[,53:64], 1, mean)  * data[,98])+ #38to49
                 (apply(data[,65:82], 1, mean)  * data[,100])+ #50to67
                 (apply(data[,83:97], 1, mean)  * data[,99]))/100*10) #68to82
data$PECI

#Checking for CMB####
library(psych)
CMB <- principal(cor(data[16:104]), nfactors = 1, rotate = "varimax")
CMB$Vaccounted #0.12 ok

#### FIRST MODEL 1 ####
# Creating our measurement model
model1_mm <- constructs(
  composite("IP", multi_items("X", 1:21)),
  composite("CO", single_item("PECI"), weights = mode_A),
  composite("Acquiescence", multi_items("AQ", 1:3)),
  composite("Compromise", multi_items("COMP", 1:3)),
  composite("Avoid", multi_items("AVO", 1:3)),
  composite("Defy", multi_items("DEF", 1:4)),
  composite("Manipulate", multi_items("MAN", 1:3)),
  composite("Control", single_item("Control_Var_2"))
  )
# Interaction constructs must be created after the measurement model is defined.
# We are using the orthogonalization method as per Henseler & Chin (2010)
model1_xm <- interactions(
  interaction_ortho("CO", "IP"))
# Structural model
#  note: interactions should be the names of its main constructs joined by a '*' in between.
model1_sm <- relationships(
  paths(from = "IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "Control", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")),
  paths(from = "CO*IP", to = c("Acquiescence", "Compromise", "Avoid", "Defy", "Manipulate")))
# Load data, assemble model, and estimate using simplePLS
model1_pls <- estimate_pls(data = data,
                         measurement_model = model1_mm,
                         interactions = model1_xm,
                         structural_model = model1_sm,
                         inner_weights = path_weighting)

summary1 <- summary(model1_pls)

summary1$iterations #Iterations
summary1$loadings #Loadings Outer Model
summary1$paths #Paths LVs
summary1$reliability #Reliability
summary1$cross_loadings #Cross-loadings
summary1$vif_items #VIF Indicators
summary1$vif_antecedents #VIF LVs
```

**Comment by storopoli** [comment] 2018-10-17 13:49
Dear @NicholasDanks 
Thank you! Unfortunately i cannot get the p-values from the LVs paths because of the impossibility of bootstrapping. But I'll wait anxiously for this issue to be discussed and resolved.

Regards,

**Comment by soumyaray** [comment] 2018-10-18 03:10
Thank you again for your assistance @storopoli 

If you choose to go with the all composites approach (as shown in the code @NicholasDanks posted), then the bootstrapping will work fine.  I don't think this will cause any concern from journals as the overwhelming majority of PLS papers only use composites (mode A or mode B), and very few expect papers to use consistent-PLS (PLSc) to model common factors (like covariance-based SEM). It's up to you of course how you wish to proceed.

We will close this Github issue when our patch is released (should be within the coming week), as the issue no longer relates to a bug in our code. We will raise the question of interactions between composites and factors with other methodologists and hopefully the community will publish a resolution some day.

**Closed** 2019-04-10 08:39 UTC
